# render.yaml
services:
  - type: web
    name: task-approver-api
    env: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm run start